"""add deleted_at to birth_charts

Revision ID: 46a9a258b2e0
Revises: 91e32f267b38
Create Date: 2026-09-28 23:49:30.638256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a9a258b2e0'
down_revision: Union[str, Sequence[str], None] = '91e32f267b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birth_charts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birth_charts', 'deleted_at')
    # ### end Alembic commands ###
